backend/api/urls.py
from django.urls import include, path
from rest_framework.routers import DefaultRouter

from .views import UserModelViewSet

app_name = 'api'

router = DefaultRouter()

router.register('users', UserModelViewSet, basename='user')

urlpatterns = [
    path('auth/', include('djoser.urls.jwt')),
    path('', include(router.urls))
]

backend/django_mem_cards/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from .views import RegistrationView

urlpatterns = [
    path('', include('homepage.urls', namespace='homepage')),
    path('api/', include('api.urls', namespace='api')),
    path('pages/', include('pages.urls', namespace='pages')),
    path('deck/', include('deck.urls', namespace='deck')),
    path('admin/', admin.site.urls),
    path('auth/', include('django.contrib.auth.urls')),
    path(
        'auth/registration/',
        RegistrationView.as_view(),
        name='registration',
    ),
]

if settings.DEBUG:
    import debug_toolbar
    # Добавить к списку urlpatterns список адресов из приложения debug_toolbar:
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

backend/pages/urls.py
from django.urls import path
from . import views

app_name = 'pages'

urlpatterns = [
    path('about/', views.description.as_view(), name='description'),
    path('tutorial/', views.tutorial.as_view(), name='tutorial'),
    path('tg/', views.ApiTokenPageView.as_view(), name='tg_bot_page_view'),
    path('tg/create_api_token/', views.create_api_token, name='create_api_token'),
    path('tg/delete_api_token/', views.delete_api_token, name='delete_api_token'),

]

backend/templates/pages/description.html
{% extends "base.html" %}

{% block title %}О проекте{% endblock %}

{% block content %}

<article>
  <h1>О проекте:</h1>
  <p>
    <b>LangMemo</b> — это онлайн-платформа, которая использует метод интервального повторения для изучения иностранных языков.
  </p>
  <p>
    Метод интервального повторения — это эффективный способ изучения иностранных языков, основанный на принципах когнитивной психологии и нейронауки. Он помогает повысить эффективность и результативность обучения, а также улучшить долгосрочное запоминание информации.
  </p>
  <p>
    Метод интервального повторения использует принцип подачи учебного материала с определёнными интервалами, что облегчает усвоение новых знаний. Система анализирует уровень знаний пользователя и определяет оптимальный интервал повторения для каждого материала.
  </p>
  <p>
    Преимущества метода интервального повторения:
    <ul>
      <li>повышение эффективности обучения</li>
      <li>улучшение запоминания</li>
      <li>адаптация к уровню знаний пользователя</li>
      <li>мотивация к регулярным занятиям</li>
      <li>удобство использования онлайн</li>
      <li>повышение эффективности обучения</li>
    </ul>
  </p>
  <p>
    <b>LangMemo</b> — ваш надёжный помощник в изучении иностранных языков.
  </p>
</article>

{% endblock %}

backend/templates/pages/tg_bot_page.html
{% extends "base.html" %}

{% block title %}Telegram бот{% endblock %}

{% block content %}

<article class="row">
  <h1>Telegram-бот</h1>
  <hr>

  <article class="col-6">
    <h2>Функции бота:</h2>
    <p>
      Возможности бота совершенствуются и будут дополнятся. На данный момент через бота вы можете получать календарь ревью на ближайшие дни в удобном формате мессенджера.
    <p>
    <h2>Как это работает:</h2>
    <p>
      <ol>
        <li>
          <b>Создайте токен.</b>
          Для работы с ботом вам нужно создать токен. Сделать это можно нажав на кнопку справа. Если вы хотите отвязать вашу учетную запись LangMemo от аккаунта в Telegram, удалите созданный токен.
        </li>
        <li>
          <b>Пришлите токен боту.</b>
          Бот доступен <a href='https://t.me/langmemo_bot'>по ссылке</a>. Для начала работы скопируйте токен с сайта и пришлите боту.
        </li>
      </ol>
  </article>

<article class="col-6">
  <div class="card">
    <h5 class="card-header bg-info-subtle">Токен</h5>
    <div class="card-body">
      {% if not user.api_token %}
      <div class="text-center">
        <b>Нет токена!</b>
        <hr class="opacity-0">
        <a href="{% url 'pages:create_api_token' %}" class="btn btn-primary">Создать токен</a>
      </div>
      {% else %}
      <div class="input-group">
        <input id="apiTokenField" type="text" class="form-control border-end-0 border-secondary" value="{{ user.api_token }}" readonly>
        <button class="btn btn-outline-secondary border-start-0" type="button" id="copyBtn">
          <i class="bi bi-clipboard" aria-hidden="true"></i>
        </button>
      </div>
      <div class="mt-3 text-center">
        <a href="{% url 'pages:delete_api_token' %}" class="btn btn-danger">Удалить токен</a>
      </div>
      <script>
        document.addEventListener('DOMContentLoaded', function () {
          const btn = document.getElementById('copyBtn');
          const field = document.getElementById('apiTokenField');
          btn.addEventListener('click', () => {
            navigator.clipboard.writeText(field.value)
              .then(() => {
                btn.classList.add('text-success');
                setTimeout(() => btn.classList.remove('text-success'), 800);
              })
              .catch(console.error);
          });
        });
      </script>
      {% endif %}
    </div>
  </div>
</article>

</article>

{% endblock %}

backend/templates/pages/tutorial.html
{% extends "base.html" %}

{% block title %}Обучение{% endblock %}

{% block content %}

{% load static %}

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="..." crossorigin="anonymous"></script>

<script>
  document.addEventListener('DOMContentLoaded', function () {
    const myCarouselElement = document.querySelector('#carouselExampleCaptions');
    const carousel = new bootstrap.Carousel(myCarouselElement, {
      touch: false
    });
  });
</script>

<article>
  <h1>Обучение</h1>
  
  <article class="row justify-content-center">
    <div class="col-9">

  <div id="carouselExampleCaptions" class="carousel slide" data-bs-theme="dark">
  <div class="carousel-indicators">
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="3" aria-label="Slide 4"></button>
  </div>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="{% static 'img/tutorial/slide_1.png' %}" class="d-block w-100">
      <div class="carousel-caption d-none d-md-block">
        <h5>Шаг 1.</h5>
        <p>Создайте колоду и добавьте в нее карточки со словами.</p>
      </div>
    </div>
    <div class="carousel-item">
      <img src="{% static 'img/tutorial/slide_2.png' %}" class="d-block w-100">
      <div class="carousel-caption d-none d-md-block">
        <h5>Шаг 2.</h5>
        <p>Изучите добавленные карточки.</p>
      </div>
    </div>
    <div class="carousel-item">
      <img src="{% static 'img/tutorial/slide_3.png' %}" class="d-block w-100">
      <div class="carousel-caption d-none d-md-block">
        <h5>Шаг 3.</h5>
        <p>Изученные карточки станут доступны для повторного изучения позже. Чем успешнее изучение - тем больше интервалы.</p>
      </div>
    </div>
    <div class="carousel-item">
      <img src="{% static 'img/tutorial/slide_4.png' %}" class="d-block w-100">
      <div class="carousel-caption d-none d-md-block">
        <h5>Шаг 4.</h5>
        <p>Продолжайте изучать карточки и добавлять новые. Удачи в обучении!</p>
      </div>
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>

</div>
</article>
</article>


{% endblock %}