backend/api/urls.py
from django.urls import include, path
from rest_framework.routers import DefaultRouter

from .views import UserModelViewSet

app_name = 'api'

router = DefaultRouter()

router.register('users', UserModelViewSet, basename='user')

urlpatterns = [
    path('auth/', include('djoser.urls.jwt')),
    path('', include(router.urls))
]

backend/deck/urls.py
from django.urls import path
from . import views

app_name = 'deck'

urlpatterns = [
    path('<int:deck_id>/review/', views.review_display, name='review_display'),
    path(
        'review_check/<int:card_id>/',
        views.review_check,
        name='review_check'
    ),
    path(
        '<int:deck_id>/create_card/',
        views.CardCreateView.as_view(),
        name='create_card'
    ),
    path(
        'delete_card/<int:card_id>/',
        views.CardDeleteView.as_view(),
        name='delete_card'
    ),
    path(
        'edit_card/<int:card_id>/',
        views.CardUpdateView.as_view(),
        name='edit_card'
    ),
    path('<int:deck_id>/', views.CardListView.as_view(), name='card_list'),
]

backend/django_mem_cards/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from .views import RegistrationView

urlpatterns = [
    path('', include('homepage.urls', namespace='homepage')),
    path('api/', include('api.urls', namespace='api')),
    path('pages/', include('pages.urls', namespace='pages')),
    path('deck/', include('deck.urls', namespace='deck')),
    path('admin/', admin.site.urls),
    path('auth/', include('django.contrib.auth.urls')),
    path(
        'auth/registration/',
        RegistrationView.as_view(),
        name='registration',
    ),
]

if settings.DEBUG:
    import debug_toolbar
    # Добавить к списку urlpatterns список адресов из приложения debug_toolbar:
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

backend/homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path(
        'create_deck/',
        views.DeckCreateView.as_view(),
        name='create_deck'
    ),
    path(
        '<int:deck_id>/delete_deck/',
        views.DeckDeleteView.as_view(),
        name='delete_deck'
    ),
    path('', views.DeckListView.as_view(), name='index'),

]

backend/deck/models.py
from django.db import models
from django.contrib.auth import get_user_model

CustomUser = get_user_model()


class Deck(models.Model):
    """Модель колоды."""
    user = models.ForeignKey(
        CustomUser,
        on_delete=models.CASCADE,
        related_name='decks'
    )
    deck_name = models.CharField(
        'Название колоды',
        max_length=50,
    )

    def __str__(self):
        return self.deck_name

    class Meta:
        ordering = ('-pk',)


class Card(models.Model):
    """Модель карты."""
    deck = models.ForeignKey(
        Deck,
        on_delete=models.CASCADE,
        related_name='cards'
    )
    question = models.CharField(
        'Текст вопроса',
        max_length=50,
    )
    # В формах методом clean() валидируем,
    # что хотя бы один из ответов не пустой
    answer_1 = models.CharField(
        'Ответ',
        max_length=50,
        null=True,
        blank=True
    )
    answer_2 = models.CharField(
        'Синоним (опционально)',
        max_length=50,
        null=True,
        blank=True
    )
    answer_3 = models.CharField(
        'Синоним (опционально)',
        max_length=50,
        null=True,
        blank=True
    )
    right_guesses = models.PositiveSmallIntegerField(
        'Количество правильных ответов',
        default=0
    )
    wrong_guesses = models.PositiveSmallIntegerField(
        'Количество неправильных ответов',
        default=0
    )
    # Автоматически рассчитывается в переопределенном методе модели save()
    winrate = models.FloatField(
        'Доля успеха',
        default=None,
        null=True,
        blank=True
    )
    # Автоматически устанавливается при создании карты
    datetime_created = models.DateTimeField(
        'Дата создания',
        auto_now_add=True
    )
    # Лучше не делать авто, т.к. дата будет ставиться и при сохранении после
    # редактирования
    datetime_reviewed = models.DateTimeField(
        'Дата последнего ревью',
        default=None,
        null=True,
        blank=True
    )
    in_queue = models.BooleanField(
        'В очереди на ревью',
        default=True
    )
    srs_level = models.PositiveSmallIntegerField(
        'Уровень SRS',
        default=0
    )
    srs_xp = models.PositiveSmallIntegerField(
        'Опыт SRS',
        default=0
    )

    def __str__(self):
        return self.question

    def save(self, *args, **kwargs):
        """При каждом сохранении карты винрейт пересчитывается."""
        try:
            self.winrate = (100 * self.right_guesses
                            / (self.right_guesses + self.wrong_guesses))
        except ZeroDivisionError:
            self.winrate = None

        super().save(*args, **kwargs)

    class Meta:
        ordering = ('-datetime_created',)

backend/deck/forms.py
from django import forms
from django.core.exceptions import ValidationError

from .models import Card, Deck


class CardForm(forms.ModelForm):
    """Форма карты."""
    class Meta:
        model = Card
        fields = ('question',
                  'answer_1',
                  'answer_2',
                  'answer_3',
                  )

    def clean(self):
        ans1 = self.cleaned_data['answer_1']
        ans2 = self.cleaned_data['answer_2']
        ans3 = self.cleaned_data['answer_3']

        if not (ans1 or ans2 or ans3):
            raise ValidationError('Введите хотя бы один ответ!')


class DeckForm(forms.ModelForm):
    """Форма колоды."""
    class Meta:
        model = Deck
        fields = ('deck_name',)

backend/deck/views.py
from django.utils import timezone
from datetime import timedelta
from random import choice
from sys import maxsize

from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import UserPassesTestMixin, LoginRequiredMixin
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse, reverse_lazy
from django.views.generic import (
    CreateView,
    DeleteView,
    ListView,
    UpdateView
)

from .models import Card, Deck
from .forms import CardForm
from .utils import damerau_levenshtein_distance as dam_lev_dist

from django_mem_cards.constants import (CARDS_PAGINATION_LIMIT,
                                        CARD_BAD_WINRATE_LIMIT,
                                        DAM_LEV_DIST_LIMIT,
                                        SRS_LEVELS,
                                        REVIEW_SUCCESS_MESSAGE,
                                        REVIEW_NOT_PERFECT_SUCCESS_MESSAGE,
                                        REVIEW_FAILURE_MESSAGE,
                                        REVIEW_NOT_IN_QUEUE_MESSAGE)


def refresh_queue(user, deck_list):
    """Функция, актуализирующая статус in_queue
    карт пользователя из deck_list."""

    cards = Card.objects.filter(
            deck__user__id=user.pk,
            deck__in=deck_list,
            in_queue=False
        )
    # Нужно сделать один запрос, апдейтящий все нужные карты,
    # а не много запросов, каждый апдейтящий одну карту.
    cards_to_update = []
    for card in cards:
        if (card.datetime_reviewed is None) or (timezone.now() - card.datetime_reviewed > timedelta(hours=SRS_LEVELS[card.srs_level]['time_interval_hrs'])):
            card.in_queue = True
            cards_to_update.append(card)

    cards.bulk_update(cards_to_update, fields=['in_queue'])


class CardListView(LoginRequiredMixin, ListView):
    """Класс, отвечающий за отображение списка карт на странице колоды."""
    model = Card
    template_name = 'deck/card_list.html'
    paginate_by = CARDS_PAGINATION_LIMIT

    def get_queryset(self):
        self.deck = get_object_or_404(
            Deck,
            pk=self.kwargs['deck_id'],
            user=self.request.user
        )

        # Для корректной отображения ответов только у кард не в очереди
        refresh_queue(user=self.request.user, deck_list=(self.deck,))

        qs = Card.objects.filter(deck=self.deck)
        return qs

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['form'] = CardForm()
        context['deck'] = self.deck
        context['card_count'] = context['deck'].cards.count()
        context['card_bad_winrate'] = CARD_BAD_WINRATE_LIMIT

        return context


class CardCreateView(LoginRequiredMixin, CreateView):
    """Класс, отвечающий за создание карты."""
    model = Card
    form_class = CardForm
    template_name = 'deck/card_list.html'
    paginate_by = CARDS_PAGINATION_LIMIT

    def get(self, *args, **kwargs):
        return redirect(reverse_lazy('homepage:index'))

    def form_valid(self, form):
        self.deck = get_object_or_404(
            Deck,
            id=self.kwargs['deck_id'],
            user=self.request.user
        )
        # Для корректной отображения ответов только у кард не в очереди
        refresh_queue(user=self.request.user, deck_list=(self.deck,))
        form.instance.deck = self.deck
        return super().form_valid(form)

    def form_invalid(self, form):
        self.deck = get_object_or_404(
            Deck,
            id=self.kwargs['deck_id'],
            user=self.request.user
        )
        # Для корректной отображения ответов только у кард не в очереди
        refresh_queue(user=self.request.user, deck_list=(self.deck,))
        return super().form_invalid(form)

    def get_context_data(self, *args, **kwargs):
        # Тут вручную передаем то же, что передается в CardListView
        context = super().get_context_data(*args, **kwargs)
        context['deck'] = self.deck
        context['card_count'] = context['deck'].cards.count()
        context['card_bad_winrate'] = CARD_BAD_WINRATE_LIMIT

        paginator = Paginator(
            Card.objects.filter(deck=context['deck']),
            self.paginate_by
        )
        page_number = self.request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        context['page_obj'] = page_obj

        return context

    def get_success_url(self):
        return reverse_lazy('deck:card_list',
                            kwargs={'deck_id': self.kwargs['deck_id']})


class CardDeleteView(UserPassesTestMixin, DeleteView):
    """Класс, отвечающий за удаление карты."""
    model = Card

    def test_func(self):
        object = self.get_object()
        self.deck_id = object.deck.id
        return object.deck.user == self.request.user

    def get_object(self, queryset=None):
        return get_object_or_404(
            Card,
            id=self.kwargs['card_id'],
        )

    def get_success_url(self):
        return reverse('deck:card_list',
                       kwargs={'deck_id': self.deck_id})


class CardUpdateView(UserPassesTestMixin, UpdateView):
    """Класс, отвечающий за удаление карты."""
    model = Card
    form_class = CardForm
    template_name_suffix = '_update_form'
    #fields = ['question', 'answer_1', 'answer_2', 'answer_3']

    def test_func(self):
        object = self.get_object()
        self.deck_id = object.deck.id
        return object.deck.user == self.request.user

    def get_object(self, queryset=None):
        return get_object_or_404(
            Card,
            id=self.kwargs['card_id'],
        )

    def get_success_url(self):
        return reverse('deck:card_list',
                       kwargs={'deck_id': self.deck_id})


@login_required
def review_display(request, deck_id):
    """Функция, отображающая очередную карту для ревью."""

    deck = get_object_or_404(
        Deck,
        id=deck_id,
        user=request.user
    )
    refresh_queue(user=request.user, deck_list=(deck,))

    cards_to_review = list(Card.objects.filter(
        in_queue=True,
        deck__id=deck_id
    ))

    if len(cards_to_review) == 0:
        return redirect(reverse('homepage:index'))

    context = {
        'reviewed_card': choice(cards_to_review)    # random.choice
    }

    return render(
        request,
        template_name='deck/review.html',
        context=context
    )


@login_required
def review_check(request, card_id):
    """Функция, проверяющая ответ на ревью и обновляющая информацию в карте."""

    if request.method == 'GET':
        return redirect(reverse_lazy('homepage:index'))

    update_fields = ['in_queue', 'datetime_reviewed',
                     'srs_xp', 'srs_level', 'winrate']

    reviewed_card = get_object_or_404(
        Card,
        id=card_id,
        deck__user=request.user
    )
    if not reviewed_card.in_queue:
        template_name = 'deck/review_not_in_queue.html'
        message_to_send = REVIEW_NOT_IN_QUEUE_MESSAGE
    else:
        min_dist = maxsize
        for ans in (reviewed_card.answer_1,
                    reviewed_card.answer_2,
                    reviewed_card.answer_3):
            if ans is not None:
                min_dist = min(
                    min_dist,
                    dam_lev_dist(
                        str.lower(request.POST['answer']),
                        str.lower(ans)
                    )
                )
        if min_dist == 0:
            template_name = 'deck/review_success.html'
            message_to_send = REVIEW_SUCCESS_MESSAGE
            reviewed_card.right_guesses += 1
            update_fields.append('right_guesses')
            if reviewed_card.srs_level < 4:
                reviewed_card.srs_xp += 1
                # По-хорошему, "больше" быть не может,
                # но на всякий случай учтем и этот случай.
                if reviewed_card.srs_xp >= SRS_LEVELS[reviewed_card.srs_level]['xp_to_next_lvl']:
                    reviewed_card.srs_level += 1
                    reviewed_card.srs_xp = 0
        elif min_dist > DAM_LEV_DIST_LIMIT:
            template_name = 'deck/review_failure.html'
            message_to_send = REVIEW_FAILURE_MESSAGE
            reviewed_card.wrong_guesses += 1
            update_fields.append('wrong_guesses')
            reviewed_card.srs_xp = 0
            if reviewed_card.srs_level > 0:
                reviewed_card.srs_level -= 1
        else:
            template_name = 'deck/review_success.html'
            message_to_send = REVIEW_NOT_PERFECT_SUCCESS_MESSAGE
            reviewed_card.right_guesses += 1
            update_fields.append('right_guesses')
            if reviewed_card.srs_level < 4:
                reviewed_card.srs_xp += 1
                # По-хорошему, "больше" быть не может,
                # но на всякий случай учтем и этот случай.
                if reviewed_card.srs_xp >= SRS_LEVELS[reviewed_card.srs_level]['xp_to_next_lvl']:
                    reviewed_card.srs_level += 1
                    reviewed_card.srs_xp = 0

        reviewed_card.datetime_reviewed = timezone.now()
        reviewed_card.in_queue = False
        reviewed_card.save(update_fields=update_fields)

    return render(
            request,
            template_name=template_name,
            context={
                'reviewed_card': reviewed_card,
                'message': message_to_send
            }
        )

backend/templates/deck/card_confirm_delete.html
{% extends "base.html" %}
{% load django_bootstrap5 %}

{% block title %}LangMemo{% endblock %}

{% block content %}

<article class="row justify-content-center">

<h1>Удалить карточку?</h1>

<div class="col-4">
  <div class="card {% if card.winrate < card_bad_winrate %}border-danger{% endif %}">
    <h5 class="card-header bg-primary-subtle">{{ card.question }}</h5>
    <div class="card-body">
      <p class="card-text {% if card.winrate < card_bad_winrate %}text-danger{% endif %}">
        Доля успеха:
        {% if card.winrate == None%}
          <b>Не было ревью</b>
        {% else %}
          <b>{{ card.winrate|floatformat:2 }} %</b>
        {% endif %}
      </p>
      <p class="card-text">
        Уровень SRS:
        {{ card.srs_level }}
      </p>
      
      {% if card.in_queue %}
        <p>
          <b>Карточка в очереди! Ответы недоступны!</b>
        </p>
      {% else %}
        <details>
          <summary>Ответы</summary>
          <ul>
            {% if card.answer_1 is not None %}
              <li>{{ card.answer_1 }}</li>
            {% endif %}

            {% if card.answer_2 is not None %}
              <li>{{ card.answer_2 }}</li>
            {% endif %}

            {% if card.answer_3 is not None %}
              <li>{{ card.answer_3 }}</li>
            {% endif %}
          </ul>
        </details>
      {% endif %}

      <hr class="opacity-0">

      <div class="hstack gap-3">
        <form method="POST" action="{% url 'deck:delete_card' card.id %}">
          {% csrf_token %}
          <div class="hstack gap-3">
            <input class="btn btn-danger" type="submit" value="Удалить">
            <a class="btn btn-outline-primary" href="{% url 'deck:card_list' card.deck.pk %}">Отмена</a>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
  
</article>

{% endblock %}

backend/templates/deck/card_list.html
{% extends "base.html" %}
{% load django_bootstrap5 %}

{% block title %}LangMemo{% endblock %}

{% block content %}




<article class="row justify-content-start">
  <h1>Состав колоды {{ deck.deck_name }} ({{ card_count }} шт.):</h1>
  <hr class="opacity-0">
  <div class="col-4">
    <div class="card">
      <h5 class="card-header bg-success-subtle">Добавить новую карточку</h5>
      <div class="card-body">
        <form method="post" autocomplete="off" action="{% url 'deck:create_card' deck.pk %}">
          {% csrf_token %}
          {% bootstrap_form form show_label=False autocomplete="off" %}
          <input class="btn btn-success" type="submit" value="Добавить карту">
        </form>
      </div>
    </div>
  </div>
</article>

<hr class="opacity-0">

<article class="row">
  

  {% for card in page_obj %}
  <div class="col-4">
    <div class="card {% if card.winrate < card_bad_winrate %}border-danger{% endif %}">
      <h5 class="card-header bg-primary-subtle">{{ card.question }}</h5>
      <div class="card-body">
        <p class="card-text {% if card.winrate < card_bad_winrate %}text-danger{% endif %}">
          Доля успеха:
          {% if card.winrate == None%}
            <b>Не было ревью</b>
          {% else %}
            <b>{{ card.winrate|floatformat:2 }} %</b>
          {% endif %}
        </p>
        <p class="card-text">
          Уровень SRS:
          {{ card.srs_level }}
        </p>
        
        {% if card.in_queue %}
          <p>
            <b>Карточка в очереди! Ответы недоступны!</b>
          </p>
        {% else %}
          <details>
            <summary>Ответы</summary>
            <ul>
              {% if card.answer_1 is not None %}
                <li>{{ card.answer_1 }}</li>
              {% endif %}

              {% if card.answer_2 is not None %}
                <li>{{ card.answer_2 }}</li>
              {% endif %}

              {% if card.answer_3 is not None %}
                <li>{{ card.answer_3 }}</li>
              {% endif %}
            </ul>
          </details>
        {% endif %}

        <hr class="opacity-0">

        <div class="hstack gap-3">
          <a href="{% url 'deck:edit_card' card.id %}" class="btn btn-outline-secondary">&#x270e; Редактировать</a>
          <a href="{% url 'deck:delete_card' card.id %}" class="btn btn-danger">Удалить</a>
          
        </div>
      </div>
    </div>
  </div>

  {% if forloop.counter|divisibleby:"3" %}
    <hr class="opacity-0">
  {% endif %}

  {% endfor %}
  
  
  
  
  
</article>
{% include "includes/paginator.html" %}
{% endblock %}

backend/templates/deck/card_update_form.html
{% extends "base.html" %}
{% load django_bootstrap5 %}

{% block title %}Memory Cards{% endblock %}

{% block content %}

<article class="row justify-content-center">
  <h1>Редактировать карточку {{ card.question }}:</h1>
  <hr class="opacity-0">
  <div class="col-4">
    <div class="card">
      <h5 class="card-header bg-success-subtle">Редактировать</h5>
      <div class="card-body">
        <form method="post" action="{% url 'deck:edit_card' card.pk %}">
          {% csrf_token %}
          {% bootstrap_form form show_label=False %}

          <div class="hstack gap-3">
            <input class="btn btn-success" type="submit" value="Сохранить">
            <a class="btn btn-outline-primary" href="{% url 'deck:card_list' card.deck.pk %}">Отмена</a>
          </div>

        </form>
      </div>
    </div>
  </div>
</article>

{% endblock %}

backend/templates/deck/deck_confirm_delete.html
{% extends "base.html" %}
{% load django_bootstrap5 %}

{% block title %}LangMemo{% endblock %}

{% block content %}

<article class="row justify-content-center">
  <h1>Удалить колоду?</h1>

  <div class="col-4">
    <div class="card {% if deck.winrate < deck_bad_winrate %}border-danger{% endif %}">
      <h5 class="card-header bg-primary-subtle">{{ deck.deck_name }}</h5>

      <div class="card-body">
        <p class="card-text">
          Карточек: 
          <b>{{ deck.card_count }}</b>
          шт.
        </p>
        <p class="card-text {% if deck.winrate < deck_bad_winrate %}text-danger{% endif %}">
          Доля успеха: 
          {% if deck.winrate == None%}
            <b>Не было ревью!</b>
          {% else %}
            <b>{{ deck.winrate|floatformat:2 }} %</b>
          {% endif %}
        </p>

        
        <div class="hstack gap-3">          
          <form method="POST" action="{% url 'homepage:delete_deck' deck.id %}">
            {% csrf_token %}
            <div class="hstack gap-3">
              <input class="btn btn-danger" type="submit" value="Удалить">
              <a class="btn btn-outline-primary" href="{% url 'homepage:index' %}">Отмена</a>
            </div>
          </form>
        </div>
        
      </div>
      
    </div>
  </div>
  
</article>
{% endblock %}

backend/templates/deck/review.html
{% extends "base.html" %}

{% block title %}LangMemo{% endblock %}

{% block content %}
<hr class="opacity-0">
<hr class="opacity-0">
<article class="row justify-content-center">
  <div class="col-6">
  <div class="card text-center">
    
    <div class="card-body">
      <h4 class="card-title">{{ reviewed_card }}</h4>
      
      <form id="review_form" name="review_form" method="POST" autocomplete="off" action="{% url 'deck:review_check' reviewed_card.id %}">
        {% csrf_token %}
        <div class="input-group mb-3">
          <input id="answer" name="answer" type="text" class="form-control" autofocus placeholder="Введите ответ" aria-label="Введите ответ" aria-describedby="text-input">
          <button class="btn btn-primary" type="submit" id="button-addon2">➤</button>
        </div>
      </form>
    </div>
    
  </div>
  </div>

  
</article>
{% endblock %}

backend/templates/deck/review_failure.html
{% extends "base.html" %}

{% block title %}LangMemo{% endblock %}

{% block content %}
<hr class="opacity-0">
<hr class="opacity-0">
<article class="row justify-content-center">
  <div class="col-8">
  <div class="card text-center">
    
    <div class="card-body">
      <h4 class="card-title">{{ reviewed_card }}</h4>
      <div class="input-group mb-3">
        <input type="text" class="form-control bg-danger-subtle" placeholder="{{ message }}" aria-label="Сообщение" aria-describedby="text-input" readonly disabled>
        <a href="{% url 'deck:review_display' reviewed_card.deck.id %}" class="btn btn-primary" id="nextBtn" type="button">➤</a>
      </div>

      <script>
        document.addEventListener("keypress", function(event) {
          if (event.key === "Enter") {
            event.preventDefault();
            document.getElementById("nextBtn").click();
          }
        });
      </script>

      <details>
        <summary>Ответы</summary>
        
        {% if reviewed_card.answer_1 is not None %}
          <p>{{ reviewed_card.answer_1 }}</p>
        {% endif %}

        {% if reviewed_card.answer_2 is not None %}
          <p>{{ reviewed_card.answer_2 }}</p>
        {% endif %}

        {% if reviewed_card.answer_3 is not None %}
          <p>{{ reviewed_card.answer_3 }}</p>
        {% endif %}
        
      </details>
    </div>
    
  </div>
  </div>

  
</article>
{% endblock %}

backend/templates/deck/review_not_in_queue.html
{% extends "base.html" %}

{% block title %}LangMemo{% endblock %}

{% block content %}
<hr class="opacity-0">
<hr class="opacity-0">
<article class="row justify-content-center">
  <div class="col-8">
  <div class="card text-center">
    
    <div class="card-body">
      <h4 class="card-title">{{ reviewed_card }}</h4>
      <div class="input-group mb-3">
        <input type="text" class="form-control bg-warning-subtle" placeholder="{{ message }}" aria-label="Сообщение" aria-describedby="text-input" readonly disabled>
        <a href="{% url 'deck:review_display' reviewed_card.deck.id %}" class="btn btn-primary" id="nextBtn" type="button">➤</a>
      </div>

      <script>
        document.addEventListener("keypress", function(event) {
          if (event.key === "Enter") {
            event.preventDefault();
            document.getElementById("nextBtn").click();
          }
        });
      </script>

    </div>
    
  </div>
  </div>

  
</article>
{% endblock %}

backend/templates/deck/review_success.html
{% extends "base.html" %}

{% block title %}LangMemo{% endblock %}

{% block content %}
<hr class="opacity-0">
<hr class="opacity-0">
<article class="row justify-content-center">
  <div class="col-8">
  <div class="card text-center">
    
    <div class="card-body">
      <h4 class="card-title">{{ reviewed_card }}</h4>
      <div class="input-group mb-3">
        <input type="text" class="form-control bg-success-subtle" placeholder="{{ message }}" aria-label="Сообщение" aria-describedby="text-input" readonly disabled>
        <a href="{% url 'deck:review_display' reviewed_card.deck.id %}" class="btn btn-primary" id="nextBtn" type="button">➤</a>
      </div>

      <script>
        document.addEventListener("keypress", function(event) {
          if (event.key === "Enter") {
            event.preventDefault();
            document.getElementById("nextBtn").click();
          }
        });
      </script>

    </div>
    
  </div>
  </div>

  
</article>
{% endblock %}