backend/api/urls.py
from django.urls import include, path
from rest_framework.routers import DefaultRouter

from .views import UserModelViewSet

app_name = 'api'

router = DefaultRouter()

router.register('users', UserModelViewSet, basename='user')

urlpatterns = [
    path('auth/', include('djoser.urls.jwt')),
    path('', include(router.urls))
]

backend/deck/urls.py
from django.urls import path
from . import views

app_name = 'deck'

urlpatterns = [
    path('<int:deck_id>/review/', views.review_display, name='review_display'),
    path(
        'review_check/<int:card_id>/',
        views.review_check,
        name='review_check'
    ),
    path(
        '<int:deck_id>/create_card/',
        views.CardCreateView.as_view(),
        name='create_card'
    ),
    path(
        'delete_card/<int:card_id>/',
        views.CardDeleteView.as_view(),
        name='delete_card'
    ),
    path(
        'edit_card/<int:card_id>/',
        views.CardUpdateView.as_view(),
        name='edit_card'
    ),
    path('<int:deck_id>/', views.CardListView.as_view(), name='card_list'),
]

backend/django_mem_cards/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from .views import RegistrationView

urlpatterns = [
    path('', include('homepage.urls', namespace='homepage')),
    path('api/', include('api.urls', namespace='api')),
    path('pages/', include('pages.urls', namespace='pages')),
    path('deck/', include('deck.urls', namespace='deck')),
    path('admin/', admin.site.urls),
    path('auth/', include('django.contrib.auth.urls')),
    path(
        'auth/registration/',
        RegistrationView.as_view(),
        name='registration',
    ),
]

if settings.DEBUG:
    import debug_toolbar
    # Добавить к списку urlpatterns список адресов из приложения debug_toolbar:
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

backend/homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path(
        'create_deck/',
        views.DeckCreateView.as_view(),
        name='create_deck'
    ),
    path(
        '<int:deck_id>/delete_deck/',
        views.DeckDeleteView.as_view(),
        name='delete_deck'
    ),
    path('', views.DeckListView.as_view(), name='index'),

]

backend/pages/urls.py
from django.urls import path
from . import views

app_name = 'pages'

urlpatterns = [
    path('about/', views.description.as_view(), name='description'),
    path('tutorial/', views.tutorial.as_view(), name='tutorial'),
    path('tg/', views.ApiTokenPageView.as_view(), name='tg_bot_page_view'),
    path('tg/create_api_token/', views.create_api_token, name='create_api_token'),
    path('tg/delete_api_token/', views.delete_api_token, name='delete_api_token'),

]

backend/homepage/views.py
from datetime import datetime, timedelta

from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.db.models import Avg, Count, Q, Sum
from django.views.generic import (
    CreateView,
    DeleteView,
    ListView
)
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from django.utils import timezone

from deck.models import Card, Deck
from deck.forms import DeckForm

from deck.views import refresh_queue

from django_mem_cards.constants import (SRS_LEVELS,
                                        DECKS_PAGINATION_LIMIT,
                                        DECK_BAD_WINRATE_LIMIT,
                                        WEEKDAYS_RUS,
                                        TOTAL_CALENDAR_DAYS)


def get_total_queue_end_of_day(plus_days, user):
    """Функция, возвращающая суммарное количество карт, которые
    будут находится в очереди в 23:59:59 в день сегодня+plus_days.
    """

    cards = Card.objects.filter(
        deck__user=user
    )
    total = 0
    for card in cards:
        if (card.datetime_reviewed is None) or (timezone.make_aware(datetime(year=timezone.now().year, month=timezone.now().month, day=timezone.now().day, hour=23, minute=59, second=59) + timedelta(days=plus_days)) - card.datetime_reviewed > timedelta(hours=SRS_LEVELS[card.srs_level]['time_interval_hrs'])):
            total += 1
    return total


class DeckListView(ListView):
    """Класс, отвечающий за отображение списка колод на главной."""

    model = Deck
    paginate_by = DECKS_PAGINATION_LIMIT
    template_name = 'homepage/index.html'

    def get_queryset(self):
        qs = Deck.objects.filter(
            user__id=self.request.user.pk
        ).annotate(
            card_count=Count('cards'),
            winrate=Avg('cards__winrate'),
            cards_in_queue=Count('cards', filter=Q(cards__in_queue=True))
        )

        refresh_queue(user=self.request.user, deck_list=qs)

        return qs.order_by('-pk')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        cards_total_now = self.get_queryset().aggregate(Sum("cards_in_queue"))['cards_in_queue__sum']
        if cards_total_now is None:
            cards_total_now = 0

        if self.request.user.is_authenticated:
            end_of_day_totals = [
                get_total_queue_end_of_day(plus_days=i, user=self.request.user)
                for i in range(TOTAL_CALENDAR_DAYS)
            ]
            calendar = [
                {'weekday': 'Сегодня',
                 'diff': end_of_day_totals[0] - cards_total_now,
                 'end_of_day': end_of_day_totals[0]},
            ] + [
                {'weekday': WEEKDAYS_RUS[(timezone.now().weekday() + i) % 7],
                 'diff': end_of_day_totals[i] - end_of_day_totals[i - 1],
                 'end_of_day': end_of_day_totals[i]}
                for i in range(1, TOTAL_CALENDAR_DAYS)
            ]
        else:
            calendar = []

        context['form'] = DeckForm()
        context['deck_bad_winrate'] = DECK_BAD_WINRATE_LIMIT
        context['cards_total_now'] = cards_total_now
        context['calendar'] = calendar

        return context


class DeckCreateView(LoginRequiredMixin, CreateView):
    """Класс, отвечающий за создание колоды."""

    model = Deck
    form_class = DeckForm
    template_name = 'homepage/index.html'

    def get(self, *args, **kwargs):
        return redirect(reverse_lazy('homepage:index'))

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('deck:card_list',
                            kwargs={'deck_id': self.object.id})


class DeckDeleteView(UserPassesTestMixin, DeleteView):
    """Класс, отвечающий за удаление колоды."""

    model = Deck

    def test_func(self):
        object = self.get_object()
        return object.user == self.request.user

    def get_object(self, queryset=None):
        return get_object_or_404(
            Deck,
            id=self.kwargs['deck_id']
        )

    def get_success_url(self):
        return reverse('homepage:index')

backend/templates/homepage/index.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% load static %}

{% block title %}LangMemo{% endblock %}

{% block content %}

{% if not user.is_authenticated %}
  <article class="row justify-content-center">
    <div class="col-6">

      <div class="card text-center">
        <div class="card-header">
          Добро пожаловать!
        </div>
        <div class="card-body">
          <h5 class="card-title">Начните эффективно изучать иностранные языки!</h5>
          <p class="card-text">Составьте колоды с лексикой, а LangMemo сделает остальное.</p>
          
          <div class="row justify-content-center">
            
              <label for="homepage-login-button">Уже есть аккаунт?</label>
              <a href="{% url 'login' %}" id="homepage-login-button" class="btn btn-primary col-6">Войти</a>
              <hr class="opacity-0">
              <hr>
              
              <a href="{% url 'registration' %}" class="btn btn-primary col-6">Зарегистрироваться</a>
            
          </div>

        </div>
        <div class="card-footer text-body-secondary">
          LangMemo
        </div>
      </div>

    </div>

  </article>
{% else %}

  <article class="row">
    <h1>Колоды:</h1>
    <hr class="opacity-0">
    <div class="col-4">
      <div class="card">
        <h5 class="card-header bg-success-subtle">Добавить новую колоду</h5>
        <div class="card-body">
          <form method="POST" autocomplete="off" action="{% url 'homepage:create_deck' %}">
            {% csrf_token %}
            {% bootstrap_form form show_label=False autocomplete="off" %}
            <input class="btn btn-success" type="submit" value="Добавить колоду">
          </form>
        </div>
      </div>
    </div>

    <div class="col-4">
      <div class="card">
        <h5 class="card-header bg-warning-subtle">Карточек в очереди: {{ cards_total_now }}</h5>
        <div class="card-body">

          <table class="table table-striped">
            <tbody>
              {% for day in calendar%}
                <tr>
                  <td>{{ day.weekday }}</td>
                  <td>+{{ day.diff }}</td>
                  <td>Всего: {{ day.end_of_day }}</td>
                </tr>
              {% endfor %}
            </tbody>
          </table>

        </div>
      </div>
    </div>

    <div class="col-4">
      <div class="card">
        <h5 class="card-header bg-info-subtle">Настройки</h5>
        <div class="card-body row justify-content-center">

          <a href="{% url 'password_change' %}" class="btn btn-outline-secondary col-8">&#x270e; Сменить пароль</a>
          <hr class="opacity-0">
          <a href="{% url 'pages:tg_bot_page_view' %}" class="btn btn-outline-secondary col-8">
            <img class="icon" src="{% static 'img/TG_logo.svg' %}" width=18 height=18>
             Telegram-бот
          </a>

        </div>
      </div>
    </div>
  </article>

  <hr class="opacity-0">

  <article class="row">
    {% for deck in page_obj %}
      <div class="col-4">
        <div class="card {% if deck.winrate < deck_bad_winrate %}border-danger{% endif %}">
          <h5 class="card-header bg-primary-subtle">{{ deck.deck_name }}</h5>

          <div class="card-body">
            <p class="card-text">
              Карточек: 
              <b>{{ deck.card_count }}</b>
              шт.
            </p>
            <p class="card-text {% if deck.winrate < deck_bad_winrate %}text-danger{% endif %}">
              Доля успеха: 
              {% if deck.winrate == None%}
                <b>Не было ревью!</b>
              {% else %}
                <b>{{ deck.winrate|floatformat:2 }} %</b>
              {% endif %}
            </p>

            
            <div class="hstack gap-3">
              <a href="{% url 'deck:card_list' deck.id %}" class="btn btn-outline-secondary">&#x270e; Редактировать</a>
              <a href="{% url 'homepage:delete_deck' deck.id %}" class="btn btn-danger">Удалить</a>
            </div>

            <hr>
            
            {% if deck.cards_in_queue == 0 %}
              <a class="btn btn-primary disabled">Очередь пуста</a>
            {% else %}
              <a href="{% url 'deck:review_display' deck.id %}" class="btn btn-primary">Изучать {{ deck.cards_in_queue }} шт.</a>
            {% endif %}

            
          </div>
          
        </div>
      </div>

    {% if forloop.counter|divisibleby:"3" %}
      <hr class="opacity-0">
    {% endif %}

    {% endfor %}
    
  </article>
  {% include "includes/paginator.html" %}

{% endif %}

{% endblock %}