backend/api/urls.py
from django.urls import include, path
from rest_framework.routers import DefaultRouter

from .views import UserModelViewSet

app_name = 'api'

router = DefaultRouter()

router.register('users', UserModelViewSet, basename='user')

urlpatterns = [
    path('auth/', include('djoser.urls.jwt')),
    path('', include(router.urls))
]

backend/django_mem_cards/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from .views import RegistrationView

urlpatterns = [
    path('', include('homepage.urls', namespace='homepage')),
    path('api/', include('api.urls', namespace='api')),
    path('pages/', include('pages.urls', namespace='pages')),
    path('deck/', include('deck.urls', namespace='deck')),
    path('admin/', admin.site.urls),
    path('auth/', include('django.contrib.auth.urls')),
    path(
        'auth/registration/',
        RegistrationView.as_view(),
        name='registration',
    ),
]

if settings.DEBUG:
    import debug_toolbar
    # Добавить к списку urlpatterns список адресов из приложения debug_toolbar:
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

backend/homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path(
        'create_deck/',
        views.DeckCreateView.as_view(),
        name='create_deck'
    ),
    path(
        '<int:deck_id>/delete_deck/',
        views.DeckDeleteView.as_view(),
        name='delete_deck'
    ),
    path('', views.DeckListView.as_view(), name='index'),

]

backend/pages/urls.py
from django.urls import path
from . import views

app_name = 'pages'

urlpatterns = [
    path('about/', views.description.as_view(), name='description'),
    path('tutorial/', views.tutorial.as_view(), name='tutorial'),
    path('tg/', views.ApiTokenPageView.as_view(), name='tg_bot_page_view'),
    path('tg/create_api_token/', views.create_api_token, name='create_api_token'),
    path('tg/delete_api_token/', views.delete_api_token, name='delete_api_token'),

]

backend/templates/includes/footer.html
<!--
<div class="row footer mt-auto" style="margin: 0;">
  <hr>
  <div class="col">
    <p class="text-center">LangMemo (C) 2024</p>
  </div>
</div>
-->

backend/templates/includes/header.html
{% load static %}
<header>
  <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top shadow-sm">
    <div class="container">
      <div 
        class="navbar-toggler" 
        type="button" 
        data-toggle="collapse" 
        data-target="#navbarNav" 
        aria-controls="navbarNav" 
        aria-expanded="false" 
        aria-label="Toggle navigation"
        >
        <span class="navbar-toggler-icon"></span>
      </div>
      <a class="navbar-brand fs-3" href="{% url 'homepage:index' %}">
        <!--
        <img src="{% static 'img/placeholder_logo2.png' %}" height="50" class="d-inline-block align-top" alt="">
        -->
        <b>LangMemo</b>
      </a>
      {% with request.resolver_match.view_name as view_name %}
        <ul class="nav  nav-pills">

          {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'pages:tutorial' %}">
                🎓 Обучение
              </a>
            </li>
          {% endif %}

          <li class="nav-item">
            <a class="nav-link" href="{% url 'pages:description' %}">
              О проекте
            </a>
          </li>

          {% if user.is_authenticated %}
            <div class="btn-group" role="group" aria-label="Basic outlined example">
              <button type="button" class="btn btn-outline-primary"><a class="text-decoration-none text-reset"
                  href="{% url 'logout' %}">Выйти</a></button>
            </div>
          {% else %}
            <div class="btn-group" role="group" aria-label="Basic outlined example">
              <button type="button" class="btn btn-outline-primary"><a class="text-decoration-none text-reset"
                  href="{% url 'login' %}">Войти</a></button>
              <button type="button" class="btn btn-outline-primary"><a class="text-decoration-none text-reset"
                  href="{% url 'registration' %}">Регистрация</a></button>
            </div>
          {% endif %}
        </ul>
      {% endwith %}
      
    </div>
  </nav>
</header>

backend/templates/includes/paginator.html
{% if page_obj.has_other_pages %}
  <nav aria-label="Page navigation" class="my-5">
    <ul class="pagination justify-content-center">
      {% if page_obj.has_previous %}
        <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
            << </a>
        </li>
      {% endif %}
      {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
      {% endfor %}
      {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}">
            >>
          </a>
        </li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
            Последняя
          </a>
        </li>
      {% endif %}
    </ul>
  </nav>
{% endif %}